package matching

import (
	"fmt"
	"math"
	"sort"
	"strings"
	"unicode"

	"github.com/Sirkolko/terraform-recovery/internal/models"
)

const (
	// minEvidence is the minimum denominator of the confidence ratio, so a
	// single weak signal can never produce a high confidence on its own.
	minEvidence = 50
	// identityPoints is awarded when a unique name matches.
	identityPoints = 60
	// maxWithoutIdentity caps the confidence of matches that are not backed
	// by a unique identifier.
	maxWithoutIdentity = 95
)

// Signal is one piece of evidence for or against a candidate.
type Signal struct {
	Label   string  `json:"label"`
	Points  int     `json:"points"`
	Max     int     `json:"max"`
	Outcome Outcome `json:"outcome"`
	Detail  string  `json:"detail,omitempty"`
}

// Candidate is one possible cloud resource for a Terraform resource.
type Candidate struct {
	CloudKey     string   `json:"cloud_key"`
	Confidence   int      `json:"confidence"`
	Identity     bool     `json:"identity,omitempty"`
	Disqualified string   `json:"disqualified,omitempty"`
	Signals      []Signal `json:"signals,omitempty"`
	earned       float64
}

type scorer struct {
	e        *engine
	t        *models.TerraformResource
	c        *models.CloudResource
	r        *Rule
	signals  []Signal
	earned   float64
	possible int
	// matched records fully matched signals, keyed by attribute name, for
	// evaluating identity keys.
	matched        map[string]bool
	relConf        map[string]int
	identity       bool
	mismatch       bool
	strictMismatch bool
}

func (s *scorer) add(label string, points float64, max int, outcome Outcome, detail string) {
	s.earned += points
	s.possible += max
	s.signals = append(s.signals, Signal{
		Label: label, Points: int(math.Round(points)), Max: max, Outcome: outcome, Detail: detail,
	})
}

func (s *scorer) info(label, detail string) {
	s.signals = append(s.signals, Signal{Label: label, Outcome: OutcomeInfo, Detail: detail})
}

// score evaluates one Terraform resource instance against one cloud resource.
func (e *engine) score(t *models.TerraformResource, c *models.CloudResource, r *Rule) Candidate {
	s := &scorer{e: e, t: t, c: c, r: r, matched: map[string]bool{}, relConf: map[string]int{}}
	for _, check := range []func() string{s.region, s.name, s.relations} {
		if reason := check(); reason != "" {
			return Candidate{CloudKey: c.Key, Disqualified: reason, Signals: s.signals}
		}
	}
	s.nameTag()
	s.tags()
	s.attrs()
	s.children()
	s.associations()
	s.resourceName()
	s.penalty()
	return s.finish()
}

func (s *scorer) region() string {
	if !s.r.Regional || s.t.Region == "" || s.c.Region == "" || s.c.Region == "global" {
		return ""
	}
	if s.t.Region != s.c.Region {
		return fmt.Sprintf("located in %s, but the provider configuration uses %s", s.c.Region, s.t.Region)
	}
	return ""
}

func (s *scorer) name() string {
	if s.r.NameAttr == "" {
		return ""
	}
	cloudName, _ := s.c.Attr(s.r.NameAttr)
	label := "Name (" + s.r.NameAttr + ")"
	if v, ok := s.t.Attr(s.r.NameAttr); ok {
		if v != cloudName {
			return fmt.Sprintf("%s is %q in the configuration but %q in AWS", s.r.NameAttr, v, cloudName)
		}
		s.matched[s.r.NameAttr] = true
		if s.r.NameUnique {
			s.identity = true
			s.add(label, identityPoints, identityPoints, OutcomeMatch, fmt.Sprintf("%q — unique identifier", v))
		} else {
			s.add(label, 40, 40, OutcomeMatch, fmt.Sprintf("%q", v))
		}
		return ""
	}
	if s.r.NamePrefixAttr != "" {
		if p, ok := s.t.Attr(s.r.NamePrefixAttr); ok {
			if !strings.HasPrefix(cloudName, p) {
				return fmt.Sprintf("name %q does not start with the configured %s %q", cloudName, s.r.NamePrefixAttr, p)
			}
			s.add("Name prefix", 25, 25, OutcomeMatch, fmt.Sprintf("%q starts with %q", cloudName, p))
			return ""
		}
	}
	unset := !s.t.IsSet(s.r.NameAttr) && (s.r.NamePrefixAttr == "" || !s.t.IsSet(s.r.NamePrefixAttr))
	if unset && s.r.GeneratedPrefix != "" && cloudName != "" {
		if strings.HasPrefix(cloudName, s.r.GeneratedPrefix) {
			s.add("Generated name", 10, 10, OutcomeMatch, fmt.Sprintf("no %s is configured and %q looks generated by Terraform", s.r.NameAttr, cloudName))
		} else {
			s.add("Generated name", 0, 10, OutcomeMismatch, fmt.Sprintf("no %s is configured, so Terraform would have generated one starting with %q; this one is %q", s.r.NameAttr, s.r.GeneratedPrefix, cloudName))
		}
	}
	return ""
}

func (s *scorer) nameTag() {
	w := s.r.NameTag
	if w == 0 {
		return
	}
	cloudName := s.c.Tags["Name"]
	tfName, ok := s.t.Tags["Name"]
	if !ok {
		if s.t.TagsKnown && cloudName != "" {
			s.add("Name tag", 0, w/4, OutcomeMismatch, fmt.Sprintf("the configuration sets no Name tag; this resource is tagged %q", cloudName))
		}
		return
	}
	switch {
	case cloudName == tfName:
		s.matched["Name"] = true
		s.add("Name tag", float64(w), w, OutcomeMatch, fmt.Sprintf("%q", tfName))
	case strings.EqualFold(cloudName, tfName):
		s.add("Name tag", 0.8*float64(w), w, OutcomePartial, fmt.Sprintf("%q vs %q (case differs)", tfName, cloudName))
	case cloudName == "":
		s.add("Name tag", 0, w, OutcomeMismatch, fmt.Sprintf("expected %q, resource has no Name tag", tfName))
	default:
		sim := nameSimilarity(tfName, cloudName)
		outcome := OutcomeMismatch
		if sim >= 0.5 {
			outcome = OutcomePartial
		}
		s.add("Name tag", 0.3*float64(w)*sim, w, outcome, fmt.Sprintf("expected %q, found %q", tfName, cloudName))
	}
}

func (s *scorer) tags() {
	w := s.r.Tags
	if w == 0 || len(s.t.Tags) == 0 {
		return
	}
	var keys []string
	for k := range s.t.Tags {
		if k == "Name" && s.r.NameTag > 0 {
			continue
		}
		keys = append(keys, k)
	}
	if len(keys) == 0 {
		return
	}
	sort.Strings(keys)
	matched := 0
	var differ []string
	for _, k := range keys {
		if v, ok := s.c.Tags[k]; ok && v == s.t.Tags[k] {
			matched++
		} else {
			differ = append(differ, k)
		}
	}
	ratio := float64(matched) / float64(len(keys))
	detail := fmt.Sprintf("%d of %d tags match", matched, len(keys))
	if len(differ) > 0 {
		detail += " (differs: " + strings.Join(limit(differ, 4), ", ") + ")"
	}
	s.add("Tags", ratio*float64(w), w, ratioOutcome(ratio), detail)
}

// tfValue returns the configured value of an attribute: the type-implied
// value, the configured literal, or the provider default when unset.
func (s *scorer) tfValue(attr string) ([]string, string) {
	if v, ok := s.r.Fixed[s.t.Type][attr]; ok {
		return []string{v}, ""
	}
	if v := s.t.Attributes[attr]; len(v) > 0 {
		return v, ""
	}
	if s.t.IsSet(attr) {
		return nil, ""
	}
	if d, ok := s.r.Defaults[attr]; ok {
		return []string{d}, " (provider default)"
	}
	return nil, ""
}

func (s *scorer) attrs() {
	for _, a := range s.r.Attrs {
		tv, suffix := s.tfValue(a.Attr)
		cv := s.c.Attributes[a.Attr]
		if len(tv) == 0 || len(cv) == 0 {
			continue
		}
		cmp := a.Compare
		if cmp == nil {
			cmp = exact
		}
		switch cmp(tv, cv) {
		case OutcomeMatch:
			s.matched[a.Attr] = true
			s.add(a.Label, float64(a.Weight), a.Weight, OutcomeMatch, joinValues(cv)+suffix)
		case OutcomePartial:
			s.add(a.Label, float64(a.Weight)/2, a.Weight, OutcomePartial,
				fmt.Sprintf("%s in configuration, %s in AWS%s", joinValues(tv), joinValues(cv), suffix))
		default:
			s.mismatch = true
			points := 0.0
			detail := fmt.Sprintf("%s in configuration, %s in AWS%s", joinValues(tv), joinValues(cv), suffix)
			if a.Strict {
				points = -float64(a.Weight)
				s.strictMismatch = true
				detail += " — cannot change without replacement"
			}
			s.add(a.Label, points, a.Weight, OutcomeMismatch, detail)
		}
	}
}

func (s *scorer) relations() string {
	for _, rel := range s.r.Relations {
		exp := s.e.expected(s.t, rel.Attr)
		if len(exp.groups) == 0 {
			if len(exp.pending) > 0 {
				s.info(rel.Label, "not evaluated until "+strings.Join(limit(exp.pending, 3), ", ")+" is mapped")
			}
			continue
		}
		actual := s.c.Relations[rel.Attr]
		if len(actual) == 0 {
			continue
		}
		found := 0
		for _, g := range exp.groups {
			if intersects(g, actual) {
				found++
			}
		}
		weight := float64(rel.Weight) * float64(exp.conf) / 100
		via := strings.Join(limit(exp.describe, 3), ", ")
		switch {
		case found == len(exp.groups) && len(actual) <= len(exp.groups):
			s.matched[rel.Attr] = true
			s.relConf[rel.Attr] = exp.conf
			s.add(rel.Label, weight, rel.Weight, OutcomeMatch, via)
		case found > 0:
			s.add(rel.Label, weight*0.5, rel.Weight, OutcomePartial,
				fmt.Sprintf("configuration: %s; AWS: %s", via, strings.Join(limit(actual, 3), ", ")))
		default:
			if rel.Strict && exp.confirmed {
				return fmt.Sprintf("%s: the configuration refers to %s, but this resource uses %s",
					strings.ToLower(rel.Label), via, strings.Join(limit(actual, 3), ", "))
			}
			s.mismatch = true
			points := 0.0
			if rel.Strict {
				points = -weight
				s.strictMismatch = true
			}
			s.add(rel.Label, points, rel.Weight, OutcomeMismatch,
				fmt.Sprintf("configuration: %s; AWS: %s", via, strings.Join(limit(actual, 3), ", ")))
		}
	}
	return ""
}

func (s *scorer) children() {
	aliases := s.c.Aliases()
	for _, ch := range s.r.Children {
		var num, den float64
		total, inside := 0, 0
		for _, ref := range s.e.referrers[s.t.Address] {
			if ref.attr != ch.Attr || !contains(ch.ChildTypes, ref.res.Type) {
				continue
			}
			m, ok := s.e.current[ref.res.Address]
			if !ok || m.cloud == nil {
				continue
			}
			w := float64(m.conf) / 100
			den += w
			total++
			if intersects(m.cloud.Relations[ch.Attr], aliases) {
				num += w
				inside++
			}
		}
		if den == 0 {
			continue
		}
		ratio := num / den
		s.add(ch.Label, ratio*float64(ch.Weight), ch.Weight, ratioOutcome(ratio),
			fmt.Sprintf("%d of %d mapped resources that reference %s belong to this one", inside, total, s.t.Address))
	}
}

func (s *scorer) associations() {
	for _, as := range s.r.Associations {
		var num, den float64
		total, found := 0, 0
		for _, ref := range s.e.referrers[s.t.Address] {
			if ref.attr != as.SelfAttr || !contains(as.AssocTypes, ref.res.Type) {
				continue
			}
			actual := s.c.Relations[as.CloudRel]
			for _, other := range ref.res.RefsFor(as.OtherAttr) {
				m, ok := s.e.current[other.Target]
				if !ok {
					continue
				}
				w := float64(m.conf) / 100
				den += w
				total++
				if intersects(m.aliases, actual) {
					num += w
					found++
				}
			}
			for _, v := range ref.res.Attributes[as.OtherAttr] {
				den++
				total++
				if contains(actual, v) {
					num++
					found++
				}
			}
		}
		if den == 0 {
			continue
		}
		ratio := num / den
		s.add(as.Label, ratio*float64(as.Weight), as.Weight, ratioOutcome(ratio),
			fmt.Sprintf("%d of %d configured associations exist in AWS", found, total))
	}
}

// resourceName compares the Terraform resource name with the resource's
// display name. It is a weak tie-breaker used only when the configuration
// has no Name tag or explicit name.
func (s *scorer) resourceName() {
	if _, ok := s.t.Tags["Name"]; ok {
		return
	}
	if s.r.NameAttr != "" && s.t.IsSet(s.r.NameAttr) {
		return
	}
	if s.c.Name == "" {
		return
	}
	sim := nameSimilarity(s.t.Name, s.c.Name)
	if sim == 0 {
		return
	}
	s.add("Resource name", 5*sim, 5, ratioOutcome(sim), fmt.Sprintf("%q resembles %q", s.t.Name, s.c.Name))
}

func (s *scorer) penalty() {
	if s.r.Penalty == nil {
		return
	}
	if points, detail := s.r.Penalty(s.c); points != 0 {
		s.mismatch = true
		s.earned += float64(points)
		s.signals = append(s.signals, Signal{Label: "Unusual for " + s.t.Type, Points: points, Outcome: OutcomeMismatch, Detail: detail})
	}
}

func (s *scorer) finish() Candidate {
	conf := 100 * s.earned / float64(max(s.possible, minEvidence))
	idConf := 0
	if s.identity {
		idConf = 100
	}
	for _, key := range s.r.IdentityKeys {
		all := true
		minRel := 100
		for _, k := range key {
			if !s.matched[k] {
				all = false
				break
			}
			if rc, ok := s.relConf[k]; ok && rc < minRel {
				minRel = rc
			}
		}
		if all {
			s.identity = true
			idConf = max(idConf, minRel)
		}
	}
	switch {
	case s.identity:
		ceiling := 97
		if !s.mismatch && s.earned >= float64(s.possible) {
			ceiling = 100
		}
		if s.mismatch {
			ceiling = 90
		}
		if s.strictMismatch {
			ceiling = 80
		}
		conf = math.Max(conf, float64(min(ceiling, idConf)))
		conf = math.Min(conf, float64(ceiling))
	default:
		conf = math.Min(conf, maxWithoutIdentity)
	}
	conf = math.Max(0, math.Min(100, conf))
	return Candidate{
		CloudKey:   s.c.Key,
		Confidence: int(math.Round(conf)),
		Identity:   s.identity,
		Signals:    s.signals,
		earned:     s.earned,
	}
}

// --- helpers ---------------------------------------------------------------------

func ratioOutcome(r float64) Outcome {
	switch {
	case r >= 0.999:
		return OutcomeMatch
	case r >= 0.5:
		return OutcomePartial
	}
	return OutcomeMismatch
}

func joinValues(v []string) string {
	if len(v) == 1 {
		return v[0]
	}
	return "[" + strings.Join(limit(v, 5), ", ") + "]"
}

func limit(v []string, n int) []string {
	if len(v) <= n {
		return v
	}
	out := append([]string{}, v[:n]...)
	return append(out, fmt.Sprintf("… +%d more", len(v)-n))
}

func contains(list []string, v string) bool {
	for _, x := range list {
		if x == v {
			return true
		}
	}
	return false
}

func intersects(a, b []string) bool {
	for _, x := range a {
		if contains(b, x) {
			return true
		}
	}
	return false
}

// nameSimilarity compares two names by their word tokens.
func nameSimilarity(a, b string) float64 {
	a, b = strings.ToLower(a), strings.ToLower(b)
	if a == "" || b == "" {
		return 0
	}
	if a == b {
		return 1
	}
	ta, tb := tokens(a), tokens(b)
	if len(ta) == 0 || len(tb) == 0 {
		return 0
	}
	inter := 0
	for t := range ta {
		if tb[t] {
			inter++
		}
	}
	union := len(ta) + len(tb) - inter
	sim := float64(inter) / float64(union)
	if inter == len(ta) || inter == len(tb) {
		// One name is fully contained in the other ("web" in "prod-web-1").
		sim = math.Max(sim, 0.6)
	}
	return sim
}

func tokens(s string) map[string]bool {
	out := map[string]bool{}
	var cur []rune
	var lastDigit bool
	flush := func() {
		if len(cur) > 0 {
			out[string(cur)] = true
			cur = cur[:0]
		}
	}
	for _, r := range s {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			d := unicode.IsDigit(r)
			if len(cur) > 0 && d != lastDigit {
				flush()
			}
			cur = append(cur, r)
			lastDigit = d
		default:
			flush()
		}
	}
	flush()
	return out
}
