package terraform

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/zclconf/go-cty/cty"
)

// RecoveryFileName is the name of the generated import configuration file.
const RecoveryFileName = "recovery.import.tf"

// GeneratedFileMarker is the first line of every file written by this tool.
// Files without it are never overwritten or deleted.
const GeneratedFileMarker = "# Generated by terraform-recovery."

// Diagnostic is a problem or notice found while analysing the configuration.
type Diagnostic struct {
	Severity string `json:"severity"` // error | warning | info
	Summary  string `json:"summary"`
	Detail   string `json:"detail,omitempty"`
	File     string `json:"file,omitempty"`
	Line     int    `json:"line,omitempty"`
}

// Diagnostic severities.
const (
	SeverityError   = "error"
	SeverityWarning = "warning"
	SeverityInfo    = "info"
)

// moduleConfig is the static content of one module directory.
type moduleConfig struct {
	dir       string
	files     int
	variables map[string]*variableConfig
	locals    map[string]hcl.Expression
	outputs   map[string]hcl.Expression
	// hiddenOutputs are sensitive or ephemeral outputs: never evaluated.
	hiddenOutputs map[string]bool
	moduleCalls   []*moduleCall
	resources     []*resourceConfig
	providers     []*providerConfig
	imports       []*importConfig
	backend       string
	hasCloud      bool
	requiredVer   string
	// attrNames holds every attribute name used in a traversal anywhere in
	// the module. Resource placeholder objects expose exactly these names.
	attrNames map[string]bool
}

type variableConfig struct {
	name     string
	def      hcl.Expression
	typeExpr hcl.Expression
	// hidden variables are sensitive or ephemeral: their values are never
	// used, they evaluate to unknown.
	hidden bool
	rng    hcl.Range
}

type moduleCall struct {
	name      string
	source    string
	count     hcl.Expression
	forEach   hcl.Expression
	providers map[string]string // child provider reference -> parent reference
	args      map[string]hcl.Expression
	rng       hcl.Range
}

type resourceConfig struct {
	typ, name   string
	count       hcl.Expression
	forEach     hcl.Expression
	providerRef string
	body        hcl.Body
	rng         hcl.Range
}

func (r *resourceConfig) key() string { return r.typ + "." + r.name }

type providerConfig struct {
	name        string
	alias       string
	region      hcl.Expression
	profile     hcl.Expression
	allowed     hcl.Expression
	forbidden   hcl.Expression
	defaultTags hcl.Expression
	roleARN     hcl.Expression
	rng         hcl.Range
}

func (p *providerConfig) ref() string {
	if p.alias != "" {
		return p.name + "." + p.alias
	}
	return p.name
}

type importConfig struct {
	to          hcl.Expression
	id          hcl.Expression
	hasForEach  bool
	hasIdentity bool
	rng         hcl.Range
}

var fileSchema = &hcl.BodySchema{
	Blocks: []hcl.BlockHeaderSchema{
		{Type: "terraform"},
		{Type: "provider", LabelNames: []string{"name"}},
		{Type: "variable", LabelNames: []string{"name"}},
		{Type: "locals"},
		{Type: "output", LabelNames: []string{"name"}},
		{Type: "module", LabelNames: []string{"name"}},
		{Type: "resource", LabelNames: []string{"type", "name"}},
		{Type: "data", LabelNames: []string{"type", "name"}},
		{Type: "ephemeral", LabelNames: []string{"type", "name"}},
		{Type: "import"},
		{Type: "moved"},
		{Type: "removed"},
		{Type: "check", LabelNames: []string{"name"}},
	},
}

// defaultAttrNames are always available on resource placeholder objects so
// that JSON configurations (which cannot be walked syntactically) still
// resolve the most common references.
var defaultAttrNames = []string{
	"id", "arn", "name", "bucket", "key_name", "identifier", "allocation_id",
	"arn_suffix", "key_id", "unique_id", "dns_name", "address", "endpoint",
	"private_ip", "public_ip", "cidr_block", "vpc_id", "subnet_id", "zone_id",
}

// isConfigFile reports whether a file name is a Terraform configuration file.
func isConfigFile(name string) bool {
	return strings.HasSuffix(name, ".tf") || strings.HasSuffix(name, ".tf.json")
}

func isOverrideFile(name string) bool {
	base := strings.TrimSuffix(strings.TrimSuffix(name, ".json"), ".tf")
	return base == "override" || strings.HasSuffix(base, "_override")
}

// IsGeneratedFile reports whether the file at path was written by this tool.
func IsGeneratedFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	buf := make([]byte, len(GeneratedFileMarker))
	n, _ := f.Read(buf)
	return string(buf[:n]) == GeneratedFileMarker
}

// parseModule reads and decodes every configuration file in dir.
func (l *loader) parseModule(dir string) *moduleConfig {
	if cfg, ok := l.modules[dir]; ok {
		return cfg
	}
	cfg := &moduleConfig{
		dir:           dir,
		variables:     map[string]*variableConfig{},
		locals:        map[string]hcl.Expression{},
		outputs:       map[string]hcl.Expression{},
		hiddenOutputs: map[string]bool{},
		attrNames:     map[string]bool{},
	}
	for _, n := range defaultAttrNames {
		cfg.attrNames[n] = true
	}
	l.modules[dir] = cfg

	entries, err := os.ReadDir(dir)
	if err != nil {
		l.addDiag(SeverityError, "Cannot read module directory", err.Error(), "", 0)
		return cfg
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() || !isConfigFile(e.Name()) {
			continue
		}
		names = append(names, e.Name())
	}
	sort.Strings(names)
	for _, name := range names {
		path := filepath.Join(dir, name)
		if name == RecoveryFileName && IsGeneratedFile(path) {
			continue // our own import file: never treated as user configuration
		}
		if isOverrideFile(name) {
			l.addDiag(SeverityWarning, "Override file ignored",
				"Override files are not merged by this tool, so matching uses the configuration without them. "+
					"Terraform's plan does use them: any difference shows up as a planned change and blocks the import.",
				l.rel(path), 0)
			continue
		}
		l.parseFile(cfg, path)
	}
	return cfg
}

func (l *loader) parseFile(cfg *moduleConfig, path string) {
	var file *hcl.File
	var diags hcl.Diagnostics
	if strings.HasSuffix(path, ".json") {
		file, diags = l.parser.ParseJSONFile(path)
	} else {
		file, diags = l.parser.ParseHCLFile(path)
	}
	l.addHCLDiags(diags)
	if file == nil || file.Body == nil {
		return
	}
	cfg.files++
	if body, ok := file.Body.(*hclsyntax.Body); ok {
		collectAttrNames(body, cfg.attrNames)
	}
	content, _, diags := file.Body.PartialContent(fileSchema)
	l.addHCLDiags(diags)
	for _, block := range content.Blocks {
		switch block.Type {
		case "terraform":
			l.decodeTerraformBlock(cfg, block)
		case "provider":
			l.decodeProvider(cfg, block)
		case "variable":
			l.decodeVariable(cfg, block)
		case "locals":
			attrs, diags := block.Body.JustAttributes()
			l.addHCLDiags(diags)
			for name, attr := range attrs {
				cfg.locals[name] = attr.Expr
			}
		case "output":
			oc, _, _ := block.Body.PartialContent(&hcl.BodySchema{
				Attributes: []hcl.AttributeSchema{{Name: "value"}, {Name: "sensitive"}, {Name: "ephemeral"}},
			})
			if attr, ok := oc.Attributes["value"]; ok {
				name := block.Labels[0]
				cfg.outputs[name] = attr.Expr
				cfg.hiddenOutputs[name] = literalTrue(oc.Attributes["sensitive"]) || literalTrue(oc.Attributes["ephemeral"])
			}
		case "module":
			l.decodeModuleCall(cfg, block)
		case "resource":
			l.decodeResource(cfg, block)
		case "import":
			l.decodeImport(cfg, block)
		}
	}
}

func (l *loader) decodeTerraformBlock(cfg *moduleConfig, block *hcl.Block) {
	tc, _, _ := block.Body.PartialContent(&hcl.BodySchema{
		Attributes: []hcl.AttributeSchema{{Name: "required_version"}},
		Blocks: []hcl.BlockHeaderSchema{
			{Type: "backend", LabelNames: []string{"type"}},
			{Type: "cloud"},
		},
	})
	if attr, ok := tc.Attributes["required_version"]; ok {
		if v, ok := literalString(attr.Expr); ok {
			cfg.requiredVer = v
		}
	}
	for _, b := range tc.Blocks {
		switch b.Type {
		case "backend":
			cfg.backend = b.Labels[0]
		case "cloud":
			cfg.hasCloud = true
		}
	}
}

func (l *loader) decodeProvider(cfg *moduleConfig, block *hcl.Block) {
	pc, _, _ := block.Body.PartialContent(&hcl.BodySchema{
		Attributes: []hcl.AttributeSchema{
			{Name: "alias"}, {Name: "region"}, {Name: "profile"},
			{Name: "allowed_account_ids"}, {Name: "forbidden_account_ids"},
		},
		Blocks: []hcl.BlockHeaderSchema{{Type: "default_tags"}, {Type: "assume_role"}},
	})
	p := &providerConfig{name: block.Labels[0], rng: block.DefRange}
	if attr, ok := pc.Attributes["alias"]; ok {
		p.alias, _ = literalString(attr.Expr)
	}
	if attr, ok := pc.Attributes["region"]; ok {
		p.region = attr.Expr
	}
	if attr, ok := pc.Attributes["profile"]; ok {
		p.profile = attr.Expr
	}
	if attr, ok := pc.Attributes["allowed_account_ids"]; ok {
		p.allowed = attr.Expr
	}
	if attr, ok := pc.Attributes["forbidden_account_ids"]; ok {
		p.forbidden = attr.Expr
	}
	for _, b := range pc.Blocks {
		switch b.Type {
		case "default_tags":
			dc, _, _ := b.Body.PartialContent(&hcl.BodySchema{Attributes: []hcl.AttributeSchema{{Name: "tags"}}})
			if attr, ok := dc.Attributes["tags"]; ok {
				p.defaultTags = attr.Expr
			}
		case "assume_role":
			ac, _, _ := b.Body.PartialContent(&hcl.BodySchema{Attributes: []hcl.AttributeSchema{{Name: "role_arn"}}})
			if attr, ok := ac.Attributes["role_arn"]; ok {
				p.roleARN = attr.Expr
			}
		}
	}
	cfg.providers = append(cfg.providers, p)
}

func (l *loader) decodeVariable(cfg *moduleConfig, block *hcl.Block) {
	vc, _, _ := block.Body.PartialContent(&hcl.BodySchema{
		Attributes: []hcl.AttributeSchema{{Name: "default"}, {Name: "type"}, {Name: "sensitive"}, {Name: "ephemeral"}},
	})
	v := &variableConfig{name: block.Labels[0], rng: block.DefRange}
	if attr, ok := vc.Attributes["default"]; ok {
		v.def = attr.Expr
	}
	if attr, ok := vc.Attributes["type"]; ok {
		v.typeExpr = attr.Expr
	}
	v.hidden = literalTrue(vc.Attributes["sensitive"]) || literalTrue(vc.Attributes["ephemeral"])
	cfg.variables[v.name] = v
}

func (l *loader) decodeModuleCall(cfg *moduleConfig, block *hcl.Block) {
	mc, remain, _ := block.Body.PartialContent(&hcl.BodySchema{
		Attributes: []hcl.AttributeSchema{
			{Name: "source"}, {Name: "version"}, {Name: "count"}, {Name: "for_each"},
			{Name: "providers"}, {Name: "depends_on"},
		},
	})
	call := &moduleCall{
		name:      block.Labels[0],
		providers: map[string]string{},
		args:      map[string]hcl.Expression{},
		rng:       block.DefRange,
	}
	if attr, ok := mc.Attributes["source"]; ok {
		call.source, _ = literalString(attr.Expr)
	}
	if attr, ok := mc.Attributes["count"]; ok {
		call.count = attr.Expr
	}
	if attr, ok := mc.Attributes["for_each"]; ok {
		call.forEach = attr.Expr
	}
	if attr, ok := mc.Attributes["providers"]; ok {
		pairs, _ := hcl.ExprMap(attr.Expr)
		for _, pair := range pairs {
			k, err1 := traversalRef(pair.Key)
			v, err2 := traversalRef(pair.Value)
			if err1 == nil && err2 == nil {
				call.providers[k] = v
			}
		}
	}
	attrs, _ := remain.JustAttributes()
	for name, attr := range attrs {
		call.args[name] = attr.Expr
	}
	cfg.moduleCalls = append(cfg.moduleCalls, call)
}

func (l *loader) decodeResource(cfg *moduleConfig, block *hcl.Block) {
	rc, _, _ := block.Body.PartialContent(&hcl.BodySchema{
		Attributes: []hcl.AttributeSchema{{Name: "count"}, {Name: "for_each"}, {Name: "provider"}},
	})
	r := &resourceConfig{typ: block.Labels[0], name: block.Labels[1], body: block.Body, rng: block.DefRange}
	if attr, ok := rc.Attributes["count"]; ok {
		r.count = attr.Expr
	}
	if attr, ok := rc.Attributes["for_each"]; ok {
		r.forEach = attr.Expr
	}
	if attr, ok := rc.Attributes["provider"]; ok {
		if ref, err := traversalRef(attr.Expr); err == nil {
			r.providerRef = ref
		}
	}
	cfg.resources = append(cfg.resources, r)
}

func (l *loader) decodeImport(cfg *moduleConfig, block *hcl.Block) {
	ic, _, _ := block.Body.PartialContent(&hcl.BodySchema{
		Attributes: []hcl.AttributeSchema{
			{Name: "to"}, {Name: "id"}, {Name: "for_each"}, {Name: "provider"}, {Name: "identity"},
		},
	})
	imp := &importConfig{rng: block.DefRange}
	if attr, ok := ic.Attributes["to"]; ok {
		imp.to = attr.Expr
	}
	if attr, ok := ic.Attributes["id"]; ok {
		imp.id = attr.Expr
	}
	_, imp.hasForEach = ic.Attributes["for_each"]
	_, imp.hasIdentity = ic.Attributes["identity"]
	cfg.imports = append(cfg.imports, imp)
}

// traversalRef converts a static reference such as aws.west to a string.
func traversalRef(expr hcl.Expression) (string, error) {
	trav, diags := hcl.AbsTraversalForExpr(expr)
	if diags.HasErrors() {
		return "", fmt.Errorf("%s", diags.Error())
	}
	var parts []string
	for _, step := range trav {
		switch s := step.(type) {
		case hcl.TraverseRoot:
			parts = append(parts, s.Name)
		case hcl.TraverseAttr:
			parts = append(parts, s.Name)
		default:
			return "", fmt.Errorf("unexpected index in reference")
		}
	}
	return strings.Join(parts, "."), nil
}

// literalTrue reports whether an optional attribute is the literal true.
func literalTrue(attr *hcl.Attribute) bool {
	if attr == nil {
		return false
	}
	v, diags := attr.Expr.Value(nil)
	return !diags.HasErrors() && v.Type() == cty.Bool && v.IsKnown() && !v.IsNull() && v.True()
}

// literalString evaluates an expression that must not reference anything.
func literalString(expr hcl.Expression) (string, bool) {
	v, diags := expr.Value(nil)
	if diags.HasErrors() || !v.IsKnown() || v.IsNull() || v.Type() != cty.String {
		return "", false
	}
	return v.AsString(), true
}

// collectAttrNames records every attribute name that appears in a traversal.
func collectAttrNames(body *hclsyntax.Body, names map[string]bool) {
	_ = hclsyntax.VisitAll(body, func(n hclsyntax.Node) hcl.Diagnostics {
		var trav hcl.Traversal
		switch e := n.(type) {
		case *hclsyntax.ScopeTraversalExpr:
			trav = e.Traversal
		case *hclsyntax.RelativeTraversalExpr:
			trav = e.Traversal
		}
		for _, step := range trav {
			if a, ok := step.(hcl.TraverseAttr); ok {
				names[a.Name] = true
			}
		}
		return nil
	})
}

// moduleManifest mirrors .terraform/modules/modules.json written by
// terraform init, which records where remote modules were installed.
type moduleManifest struct {
	Modules []struct {
		Key    string `json:"Key"`
		Source string `json:"Source"`
		Dir    string `json:"Dir"`
	} `json:"Modules"`
}

func loadManifest(root string) map[string]string {
	out := map[string]string{}
	data, err := os.ReadFile(filepath.Join(root, ".terraform", "modules", "modules.json"))
	if err != nil {
		return out
	}
	var m moduleManifest
	if json.Unmarshal(data, &m) != nil {
		return out
	}
	for _, mod := range m.Modules {
		if mod.Key == "" {
			continue
		}
		dir := mod.Dir
		if !filepath.IsAbs(dir) {
			dir = filepath.Join(root, dir)
		}
		out[mod.Key] = filepath.Clean(dir)
	}
	return out
}

func isLocalSource(source string) bool {
	return source == "." || source == ".." ||
		strings.HasPrefix(source, "./") || strings.HasPrefix(source, "../") ||
		strings.HasPrefix(source, `.\`) || strings.HasPrefix(source, `..\`)
}
