package terraform

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"
)

// ImportSpec is one import block to generate.
type ImportSpec struct {
	Address string `json:"address"`
	ID      string `json:"id"`
	Comment string `json:"comment,omitempty"`
}

// RenderImports renders import blocks as HCL. Addresses are parsed and
// re-emitted as traversals and IDs as escaped string literals, so no value is
// ever concatenated into the generated configuration.
func RenderImports(specs []ImportSpec, header []string) ([]byte, error) {
	f := hclwrite.NewEmptyFile()
	body := f.Body()
	body.AppendUnstructuredTokens(commentTokens(GeneratedFileMarker))
	for _, h := range header {
		body.AppendUnstructuredTokens(commentTokens("# " + h))
	}
	seen := map[string]bool{}
	for _, s := range specs {
		trav, err := ParseAddress(s.Address)
		if err != nil {
			return nil, err
		}
		if strings.TrimSpace(s.ID) == "" {
			return nil, fmt.Errorf("empty import ID for %s", s.Address)
		}
		if seen[s.Address] {
			return nil, fmt.Errorf("duplicate import for %s", s.Address)
		}
		seen[s.Address] = true
		body.AppendNewline()
		if s.Comment != "" {
			body.AppendUnstructuredTokens(commentTokens("# " + s.Comment))
		}
		blk := body.AppendNewBlock("import", nil)
		blk.Body().SetAttributeTraversal("to", trav)
		blk.Body().SetAttributeValue("id", cty.StringVal(s.ID))
	}
	out := hclwrite.Format(f.Bytes())
	if err := verifyRendered(out, specs); err != nil {
		return nil, err
	}
	return out, nil
}

func commentTokens(text string) hclwrite.Tokens {
	clean := strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return ' '
		}
		return r
	}, text)
	return hclwrite.Tokens{{Type: hclsyntax.TokenComment, Bytes: []byte(clean + "\n")}}
}

// verifyRendered parses the generated file back and checks that it contains
// exactly the requested import blocks. It guards against any escaping bug.
func verifyRendered(src []byte, specs []ImportSpec) error {
	file, diags := hclsyntax.ParseConfig(src, RecoveryFileName, hcl.InitialPos)
	if diags.HasErrors() {
		return fmt.Errorf("generated import file does not parse: %s", diags.Error())
	}
	content, diags := file.Body.Content(&hcl.BodySchema{Blocks: []hcl.BlockHeaderSchema{{Type: "import"}}})
	if diags.HasErrors() {
		return fmt.Errorf("generated import file is invalid: %s", diags.Error())
	}
	if len(content.Blocks) != len(specs) {
		return fmt.Errorf("generated import file has %d blocks, expected %d", len(content.Blocks), len(specs))
	}
	for i, blk := range content.Blocks {
		attrs, diags := blk.Body.JustAttributes()
		if diags.HasErrors() {
			return fmt.Errorf("generated import block is invalid: %s", diags.Error())
		}
		trav, d := hcl.AbsTraversalForExpr(attrs["to"].Expr)
		if d.HasErrors() {
			return fmt.Errorf("generated import target is invalid: %s", d.Error())
		}
		addr, err := formatTraversal(trav)
		if err != nil {
			return err
		}
		id, d := attrs["id"].Expr.Value(nil)
		if d.HasErrors() || id.Type() != cty.String {
			return fmt.Errorf("generated import id is invalid")
		}
		want, _ := NormalizeAddress(specs[i].Address)
		if addr != want || id.AsString() != specs[i].ID {
			return fmt.Errorf("generated import block %d does not round-trip (%s, %q)", i, addr, id.AsString())
		}
	}
	return nil
}

// RecoveryFilePath returns the path of the generated import file.
func RecoveryFilePath(dir string) string { return filepath.Join(dir, RecoveryFileName) }

// WriteRecoveryFile writes recovery.import.tf into the project root. It
// refuses to replace a file that was not generated by this tool or that is
// a symbolic link.
func WriteRecoveryFile(dir string, content []byte) (string, error) {
	path := RecoveryFilePath(dir)
	if err := checkReplaceable(path); err != nil {
		return "", err
	}
	tmp, err := os.CreateTemp(dir, ".recovery.import.tf.*")
	if err != nil {
		return "", err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return "", err
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return "", err
	}
	return path, nil
}

// RemoveRecoveryFile deletes recovery.import.tf if it was generated by this tool.
func RemoveRecoveryFile(dir string) (bool, error) {
	path := RecoveryFilePath(dir)
	if _, err := os.Lstat(path); errors.Is(err, fs.ErrNotExist) {
		return false, nil
	}
	if err := checkReplaceable(path); err != nil {
		return false, err
	}
	if err := os.Remove(path); err != nil {
		return false, err
	}
	return true, nil
}

func checkReplaceable(path string) error {
	info, err := os.Lstat(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if info.Mode()&fs.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return fmt.Errorf("%s is not a regular file; refusing to modify it", path)
	}
	if !IsGeneratedFile(path) {
		return fmt.Errorf("%s exists and was not generated by terraform-recovery; refusing to overwrite it", path)
	}
	return nil
}
