package terraform

import (
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
	"sort"
)

// Plan actions as classified by this tool.
const (
	ActionImport        = "import"         // import, no changes
	ActionImportUpdate  = "import-update"  // import followed by an in-place update
	ActionImportReplace = "import-replace" // import followed by a replacement
	ActionCreate        = "create"
	ActionUpdate        = "update"
	ActionReplace       = "replace"
	ActionDelete        = "delete"
	ActionForget        = "forget"
)

// PlanResource is one resource with a planned action.
type PlanResource struct {
	Address  string   `json:"address"`
	Action   string   `json:"action"`
	ImportID string   `json:"import_id,omitempty"`
	Changed  []string `json:"changed,omitempty"` // attribute names only, never values
	Reason   string   `json:"reason,omitempty"`
	// Account is the AWS account of an imported resource, taken from its ARN.
	Account string `json:"account,omitempty"`
}

// PlanAnalysis summarises a saved plan.
type PlanAnalysis struct {
	TerraformVersion string         `json:"terraform_version,omitempty"`
	Errored          bool           `json:"errored"`
	Import           int            `json:"import"`
	Add              int            `json:"add"`
	Change           int            `json:"change"`
	Destroy          int            `json:"destroy"`
	Forget           int            `json:"forget"`
	Resources        []PlanResource `json:"resources"`
	// ImportOnly is true when the plan imports resources and changes
	// nothing: the only kind of plan this tool will apply.
	ImportOnly bool `json:"import_only"`
	// MissingImports lists expected imports that the plan does not perform.
	MissingImports []string `json:"missing_imports,omitempty"`
	// UnexpectedImports lists imports that were not generated by this tool.
	UnexpectedImports []string `json:"unexpected_imports,omitempty"`
	// MismatchedImports lists addresses imported with a different ID.
	MismatchedImports []string `json:"mismatched_imports,omitempty"`
	// Accounts lists the AWS accounts the imported resources belong to,
	// as far as their ARNs reveal it.
	Accounts []string `json:"accounts,omitempty"`
}

var arnAccount = regexp.MustCompile(`^arn:[a-z0-9-]+:[a-z0-9-]+:[a-z0-9-]*:([0-9]{12}):`)

// accountOf returns the account ID in the "arn" attribute of a planned value.
func accountOf(after json.RawMessage) string {
	var v struct {
		ARN string `json:"arn"`
	}
	if json.Unmarshal(after, &v) != nil {
		return ""
	}
	if m := arnAccount.FindStringSubmatch(v.ARN); m != nil {
		return m[1]
	}
	return ""
}

// HasChanges reports whether the plan would create, change or destroy anything.
func (p *PlanAnalysis) HasChanges() bool {
	return p.Add > 0 || p.Change > 0 || p.Destroy > 0 || p.Forget > 0
}

type planJSON struct {
	TerraformVersion string `json:"terraform_version"`
	Errored          bool   `json:"errored"`
	ResourceChanges  []struct {
		Address      string `json:"address"`
		Mode         string `json:"mode"`
		ActionReason string `json:"action_reason"`
		Change       struct {
			Actions         []string        `json:"actions"`
			Before          json.RawMessage `json:"before"`
			After           json.RawMessage `json:"after"`
			AfterUnknown    json.RawMessage `json:"after_unknown"`
			BeforeSensitive json.RawMessage `json:"before_sensitive"`
			AfterSensitive  json.RawMessage `json:"after_sensitive"`
			Importing       *struct {
				ID string `json:"id"`
			} `json:"importing"`
		} `json:"change"`
	} `json:"resource_changes"`
}

// AnalyzePlan classifies the output of `terraform show -json <plan>`.
// expected maps each address this tool asked to import to its import ID.
func AnalyzePlan(data []byte, expected map[string]string) (*PlanAnalysis, error) {
	var p planJSON
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("cannot parse plan JSON: %w", err)
	}
	a := &PlanAnalysis{TerraformVersion: p.TerraformVersion, Errored: p.Errored}
	imported := map[string]string{}
	for _, rc := range p.ResourceChanges {
		if rc.Mode == "data" {
			continue
		}
		importing := rc.Change.Importing != nil
		res := PlanResource{Address: rc.Address, Reason: rc.ActionReason}
		if importing {
			res.ImportID = rc.Change.Importing.ID
			imported[rc.Address] = res.ImportID
			a.Import++
			res.Account = accountOf(rc.Change.After)
			if res.Account != "" && !containsString(a.Accounts, res.Account) {
				a.Accounts = append(a.Accounts, res.Account)
			}
		}
		switch actionKey(rc.Change.Actions) {
		case "no-op":
			if !importing {
				continue
			}
			res.Action = ActionImport
		case "create":
			res.Action = ActionCreate
			a.Add++
		case "update":
			res.Action = ActionUpdate
			if importing {
				res.Action = ActionImportUpdate
			}
			a.Change++
		case "delete,create", "create,delete":
			res.Action = ActionReplace
			if importing {
				res.Action = ActionImportReplace
			}
			a.Add++
			a.Destroy++
		case "delete":
			res.Action = ActionDelete
			a.Destroy++
		case "forget":
			res.Action = ActionForget
			a.Forget++
		case "read":
			continue
		default:
			res.Action = actionKey(rc.Change.Actions)
			a.Change++
		}
		if res.Action != ActionImport && res.Action != ActionCreate && res.Action != ActionDelete {
			res.Changed = changedAttributes(rc.Change.Before, rc.Change.After, rc.Change.AfterUnknown)
		}
		a.Resources = append(a.Resources, res)
	}
	sort.SliceStable(a.Resources, func(i, j int) bool {
		ri, rj := actionRank(a.Resources[i].Action), actionRank(a.Resources[j].Action)
		if ri != rj {
			return ri < rj
		}
		return NaturalLess(a.Resources[i].Address, a.Resources[j].Address)
	})
	for addr, id := range expected {
		got, ok := imported[addr]
		switch {
		case !ok:
			a.MissingImports = append(a.MissingImports, addr)
		case got != id:
			a.MismatchedImports = append(a.MismatchedImports, addr)
		}
	}
	for addr := range imported {
		if _, ok := expected[addr]; !ok {
			a.UnexpectedImports = append(a.UnexpectedImports, addr)
		}
	}
	sort.Strings(a.MissingImports)
	sort.Strings(a.MismatchedImports)
	sort.Strings(a.UnexpectedImports)
	sort.Strings(a.Accounts)
	a.ImportOnly = !a.Errored && !a.HasChanges() && a.Import > 0 && len(a.MismatchedImports) == 0
	return a, nil
}

func containsString(list []string, v string) bool {
	for _, x := range list {
		if x == v {
			return true
		}
	}
	return false
}

func actionKey(actions []string) string {
	out := ""
	for i, a := range actions {
		if i > 0 {
			out += ","
		}
		out += a
	}
	return out
}

// actionRank orders the most dangerous actions first.
func actionRank(action string) int {
	switch action {
	case ActionDelete:
		return 0
	case ActionReplace, ActionImportReplace:
		return 1
	case ActionForget:
		return 2
	case ActionCreate:
		return 3
	case ActionUpdate, ActionImportUpdate:
		return 4
	}
	return 5
}

// changedAttributes returns the names of top-level attributes that differ.
// Values are deliberately not returned: they may be sensitive.
func changedAttributes(before, after, afterUnknown json.RawMessage) []string {
	var b, a, au map[string]any
	_ = json.Unmarshal(before, &b)
	_ = json.Unmarshal(after, &a)
	_ = json.Unmarshal(afterUnknown, &au)
	keys := map[string]bool{}
	for k := range b {
		keys[k] = true
	}
	for k := range a {
		keys[k] = true
	}
	for k := range au {
		keys[k] = true
	}
	var out []string
	for k := range keys {
		if unknown, ok := au[k].(bool); ok && unknown {
			out = append(out, k)
			continue
		}
		if !reflect.DeepEqual(b[k], a[k]) {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}
